### ISSUE TITLE
Upgrade react-dom to version 16.3.3 or later

### ISSUE THREAD

**Issue by Usamaliaquat123** [5-StarDesigners/this-or-that#1]
Please Upgrade react-dom to version 16.3.3 or later 
  For example: 
` "dependencies": 
                {   
                         "react-dom": ">=16.3.3" 
                }
`

Future changes in your app may down you packages. That's refelect your application compilation errors

**Comment by syedatifgd** [comment]
No need as of now.

**Comment by syedatifgd** [comment]
Yes I'm aware of that, will do as soon as possible.
